name: C/C++ CI
permissions:
  contents: write

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  windows:
    name: 'Windows'
    runs-on: windows-2022

    steps:
      - name: Configure
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17'

      - name: Build
        run: |
          msbuild msvc/jk_botti.sln -p:Configuration=Release /t:Build /p:Platform=Win32

      - name: Create zip
        run: |
          copy msvc\Release\jk_botti.dll addons\jk_botti\dlls\jk_botti_mm.dll
          copy msvc\Release\jk_botti.pdb addons\jk_botti\dlls\jk_botti_mm.pdb
          Compress-Archive -Path addons\* -Destination addons.zip

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win32
          path: |
            addons.zip

  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    needs: [windows]

    steps:
      - name: Deploying windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: win32

      - name: Publish artifacts
        uses: softprops/action-gh-release@v2
        id: publish-job
        if: |
          startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.dll
            *.pdb
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}

